name: 'igrpplatformprocessmanagement-api-service'

networks:
  default:
    name: igrpplatformprocessmanagement
    external: false

services:

  postgres-igrpplatformprocessmanagement-api-service:
      image: postgres:17-alpine
      container_name: postgres-igrpplatformprocessmanagement-api-service
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DATABASE}
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      volumes:
        - postgres-data-17-igrpplatformprocessmanagement-api-service:/var/lib/postgresql/data
      restart: unless-stopped

  igrpplatformprocessmanagement-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: igrpplatformprocessmanagement-service
    env_file:
      - .env
    depends_on:
      - postgres-igrpplatformprocessmanagement-api-service
    environment:
      - SERVER_PORT=${SERVICE_PORT}
      - SERVICE_NAME=igrpplatformprocessmanagement-service
      - SPRING_ACTIVE_PROFILE=${SERVICE_PROFILE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - ENABLE_SWAGGER=${ENABLE_SWAGGER}
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    #restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

volumes:
  postgres-data-17-igrpplatformprocessmanagement-api-service:
    driver: local
